import FieldText from './FieldText'
import FieldCheckbox from './FieldCheckbox'
export const signin = {
   title: 'Sign in to Give Star',
   subtitle: '',
   button: 'Sign in',
   buttonIcon: '',
   method: 'post',
   next: {
      title: '',
   },
   previous: {
      title: '',
   },
   help: {
      title: 'TROUBLE SIGNING UP?',
      action: '',
      href: '',
   },
   fields: [
      {
         name: 'Email',
         value: 'ant@there.com',
         description: '',
         error: '',
         valid: '',
         placeholder: 'Email',
         type: 'email',
         required: true,
         component: FieldText,
         disabled: false,
         hidden: false,
      },
      {
         name: 'Password',
         value: '@Ahandsomepassword333',
         description: '',
         error: '',
         valid: '',
         placeholder: 'Password',
         type: 'password',
         required: true,
         component: FieldText,
         disabled: false,
         hidden: false,
      },
   ],
}

export const signup = {
   title: 'Sign in to Give Star',
   subtitle: '',
   button: 'Sign up',
   buttonIcon: '',
   method: 'post',
   next: {
      title: '',
   },
   previous: {
      title: '',
   },
   help: {
      title: '',
   },
   fields: [
      {
         name: 'FullName',
         value: '',
         description: '',
         error: '',
         valid: '',
         placeholder: 'Full Name',
         type: 'text',
         required: true,
         component: FieldText,
         disabled:false,
         hidden:false,
      },
      
      {
         name: 'FirstName',
         value: '',
         description: '',
         error: '',
         valid: '',
         placeholder: 'First Name',
         type: 'text',
         required: false,
         component: FieldText,
         disabled:false,
         hidden:true,
      },
      {
         name: 'LastName',
         value: '',
         description: '',
         error: '',
         valid: '',
         placeholder: 'Last Name',
         type: 'text',
         required: false,
         component: FieldText,
         disabled:false,
         hidden:true,
      },
      {
         name: 'Email',
         value: '',
         description: '',
         error: '',
         valid: '',
         placeholder: 'Email',
         type: 'email',
         required: true,
         component: FieldText,
         disabled:false,
         hidden:false,
      },
      {
         name: 'Password',
         value: '',
         description: '',
         error: '',
         valid: '',
         placeholder: 'Password',
         type: 'password',
         required: true,
         component: FieldText,
         disabled:false,
         hidden:false,
      },
      {
         name: 'ConfirmPassword',
         value: '',
         description: '',
         error: '',
         valid: '',
         placeholder: 'Confirm Password',
         type: 'password',
         required: true,
         component: FieldText,
         disabled:false,
         hidden:false,
      },
      {
         name: 'SignupRequest',
         value: '',
         description: '',
         error: '',
         valid: '',
         placeholder: 'Signup Request',
         type: 'checkbox',
         required: true,
         component: FieldCheckbox,
         terms: (
            <>
               <span className='text-black'>I agree to </span>Givestar Terms of
               Use
            </>
         ),
         href: '#',
      },
   ],
}
export const restorePassword = {}
